name: 友链移除
description: 移除已有友链
labels: [friend-link/remove]
body:
  - type: markdown
    attributes:
      value: |
        用于移除已有友链

  - type: input
    id: originalIssueId
    attributes:
      label: 原始申请 Issue 编号
      description: 申请友链时的 Issue 编号（如 123）
      placeholder: 例如：123
    validations:
      required: true

  - type: textarea
    id: comment
    attributes:
      label: 移除原因或说明
      placeholder: 例如：站点已关闭

  - type: checkboxes
    id: terms
    attributes:
      label: 确认
      options:
        - label: 我确认以上操作
          required: true
